# Generated by Django 4.2.7 on 2023-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM core_movie_actors;"
            "DELETE FROM core_actor;"
            "DELETE FROM core_movie;"
        ),
        migrations.AddField(
            model_name="actor",
            name="csfd_id",
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
